## YAml
version: '3.7'

services:

    ############### SERVER
    ssrserver:
      container_name: siteotemplate
      restart: always
      networks:
        siteo_template_network:
         aliases:
          - siteotemplate.siteo_template_network

      build:
        context: ./
      #  dockerfile: ./docker/Dockerfile-webpack-dev
      expose:
        - "8080"
      #ports:
      #  - "8080:8080"
      volumes:
        - ./:/app
        - /app/node_modules
      entrypoint:
        - npm
        - run
        - server

      env_file: ./main.env


# network siteo_network must be  created
networks:
  siteo_template_network:
    external:
      name: siteo_network
