## YAml
version: '3.7'

services:

    ############### SERVER
    siteotemplate:
      container_name: siteotemplate
      networks:
        siteo_api_network:
         aliases:
          - siteotemplate.siteo_template_network

      build:
        context: ./
      #  dockerfile: ./docker/Dockerfile-webpack-dev
      expose:
        - 8080
      ports:
        - "8080:8080"
      volumes:
      #  - ../siteo_public/account:/app/public
        - ./dist:/app/dist
        - ./src:/app/src
        - ./build:/app/build
        - ./ssr:/app/ssr
        - ./public:/app/public
        #- ./dist:/app/dist
      entrypoint:
        - npm
        - run
        - server

      env_file: ../siteo_configs/siteo-template/template.env



networks:
  siteo_template_network:
    external:
      name: siteo_network
