## YAML Template.
#docker run --rm  -v /var/www/account/siteo-account/public:/app/public -v /var/www/account/siteo-account/dist:/app/dist  account
version: '3.7'
services:
    webpackfrontend:
      container_name: webpackfrontend
      build:
        context: ./
      #  dockerfile: ./docker/Dockerfile-webpack-dev
      volumes:
        - ./:/app
        - /app/node_modules
      entrypoint:
        - npm
        - run
        - frontend
      env_file: ./main.env

#############################
  ########
    webpackplugins:
      container_name: webpackplugins
      build:
        context: ./
      #  dockerfile: ./docker/Dockerfile-webpack-dev
      volumes:
        - ./:/app
        - /app/node_modules

      entrypoint:
        - npm
        - run
        - plugins
      env_file: ./main.env
    ########
    webpackssr:
      container_name: webpackssr
      build:
        context: ./
      #  dockerfile: ./docker/Dockerfile-webpack-dev
      volumes:
        - ./:/app
        - /app/node_modules
      entrypoint:
        - npm
        - run
        - backend
      env_file: ./main.env
