## YAML Template.
#docker run --rm  -v /var/www/account/siteo-account/public:/app/public -v /var/www/account/siteo-account/dist:/app/dist  account
version: '3.7'
services:
    siteo_frontend:
      container_name: siteo_frontend
      build:
        context: ./
      #  dockerfile: ./docker/Dockerfile-webpack-dev
      volumes:
        - ./:/app
        - /app/node_modules
      entrypoint:
        - npm
        - run
        - frontend
      env_file: ./main.env

#############################
   ########
    siteo_ssr:
      container_name: siteo_ssr
      build:
        context: ./
      #  dockerfile: ./docker/Dockerfile-webpack-dev
      volumes:
        - ./:/app
        - /app/node_modules
      entrypoint:
        - npm
        - run
        - backend
      env_file: ./main.env
